"""
Simple static display example - Tests metadata file generation.

This example creates a simple display with 5 panels and verifies that
all required files are generated correctly (displayInfo.json, metaData.json, metaData.js).
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

from trelliscope import Display
from trelliscope.meta import FactorMeta, NumberMeta


def create_simple_plot(category, value):
    """Create a simple bar plot."""
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.bar([category], [value], color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'][ord(category) - ord('A')])
    ax.set_ylim(0, 35)
    ax.set_title(f"Category {category}")
    ax.set_ylabel("Value")
    plt.tight_layout()
    return fig


def main():
    """Create and write simple static display."""
    # Create data
    data = {
        "category": ["A", "B", "C", "D", "E"],
        "value": [10, 25, 15, 30, 20],
        "panel": []  # Will be populated with figures
    }

    # Create matplotlib figures
    for cat, val in zip(data["category"], data["value"]):
        fig = create_simple_plot(cat, val)
        data["panel"].append(fig)

    df = pd.DataFrame(data)

    # Create display
    print("Creating display...")
    display = Display(df, name="simple_static", description="Simple Static Panel Example")

    # Set panel column
    display.set_panel_column("panel")

    # Add meta variables
    display.add_meta_variable(
        FactorMeta(varname="category", label="Category", levels=["A", "B", "C", "D", "E"])
    )
    display.add_meta_variable(
        NumberMeta(varname="value", label="Value")
    )

    # Set default layout
    display.set_default_layout(ncol=3, nrow=None, arrangement="row")
    display.set_default_labels(["category", "value"])

    # Write display (automatically generates index.html)
    output_dir = Path("examples/output/simple_static_test")
    print(f"Writing display to {output_dir}...")
    display.write(output_path=output_dir, force=True, viewer_debug=False)

    # Verify files were created (multi-display structure)
    print("\nVerifying files...")

    # Root files
    root_files = [
        output_dir / "index.html",
        output_dir / "config.json",
    ]

    # Display directory files
    display_dir = output_dir / "displays" / "simple_static"
    display_files = [
        output_dir / "displays" / "displayList.json",
        display_dir / "displayInfo.json",
        display_dir / "metaData.json",
        display_dir / "metaData.js",
        display_dir / "metadata.csv",
    ]

    # Panel files
    panel_files = [
        display_dir / "panels" / "0.png",
        display_dir / "panels" / "1.png",
        display_dir / "panels" / "2.png",
        display_dir / "panels" / "3.png",
        display_dir / "panels" / "4.png",
    ]

    required_files = root_files + display_files + panel_files

    all_exist = True
    for file_path in required_files:
        exists = file_path.exists()
        status = "✓" if exists else "✗"
        try:
            rel_path = file_path.relative_to(output_dir)
        except ValueError:
            rel_path = file_path
        print(f"  {status} {rel_path}")
        if not exists:
            all_exist = False

    if all_exist:
        print("\n✓ All required files created successfully!")
        print(f"\nTo view the display:")
        print(f"  1. cd {output_dir}")
        print(f"  2. python -m http.server 8000")
        print(f"  3. Open http://localhost:8000/")
        print(f"\nNote: index.html was automatically generated by Display.write()")
    else:
        print("\n✗ Some files are missing!")

    # Close all figures
    plt.close('all')


if __name__ == "__main__":
    main()
